
import pandas as pd

# --- Dictionaries and Lists ---

item_to_category = {
    # Bottle Beer
    "Can Austin Cider": ["Cans / Prem Bottle"],
    "Bud Light Bottle": ["Dom Bottle"],
    "Budweiser Bottle": ["Dom Bottle"],
    "Coors Bottle": ["Dom Bottle"],
    "Coors Light Bottle": ["Dom Bottle"],
    "Michelob Ultra Bottle": ["Dom Bottle"],
    "Miller Light Bottle": ["Dom Bottle"],
    "O'Douls Bottle": ["Dom Bottle"],
    "Domestic Bucket": ["Dom Bucket"],
    "Zippa Rona": ["Zipparona"],
    "Angry Orchard Bottle": ["Cans / Prem Bottle"],
    "CAN Austin Cider ": ["Cans / Prem Bottle"],
    "College Street Big Blue Van Bottle": ["Cans / Prem Bottle"],
    "Corona N/A Bottle": ["Cans / Prem Bottle", "Mexi Bottles"],
    "Corona Bottle": ["Cans / Prem Bottle", "Mexi Bottles"],
    "Corona Premier Bottle": ["Cans / Prem Bottle", "Mexi Bottles"],
    "Cornonita Bucket (Zipps)": ["Coronita Bucket $24"],
    "Dos XX Lager Bottle ": ["Cans / Prem Bottle", "Mexi Bottles"],
    "CAN Guinness ": ["Cans / Prem Bottle"],
    "CAN Heineken Zero ": ["Cans / Prem Bottle"],
    "Modelo Especial Bottle": ["Cans / Prem Bottle", "Mexi Bottles"],
    "Pacifico": ["Cans / Prem Bottle", "Mexi Bottles"],
    "Truly Pineapple ": ["Hard Seltzer"],
    "Truly Pineapple (Fs) ": ["Hard Seltzer"],
    "Truly Wild Berry": ["Hard Seltzer"],
    "Truly Wild Berry (Fs)": ["Hard Seltzer"],
    "CAN Twisted Tea ": ["Cans / Prem Bottle"],
    "CAN White Claw Black Cherry ": ["Hard Seltzer"],
    "CAN White Claw Black Cherry (Fs) ": ["Hard Seltzer"],
    "CAN White Claw Mango ": ["Hard Seltzer"],
    "CAN White Claw Peach ": ["Hard Seltzer"],
    "CAN White Claw Peach (Fs) ": ["Hard Seltzer"],
    "Can Guinness": ["Cans / Prem Bottle"],
    "Can Heineken Zero": ["Cans / Prem Bottle"],
    "Can Twisted Tea": ["Cans / Prem Bottle"],
    "Can White Claw Black Cherry": ["Hard Seltzer"],
    "Can White Claw Black Cherry (Fs)": ["Hard Seltzer"],
    "Can White Claw Mango": ["Hard Seltzer"],
    "Can White Claw Mango (Fs)": ["Hard Seltzer"],
    "Can White Claw Peach": ["Hard Seltzer"],
    "Can White Claw Peach (Fs)": ["Hard Seltzer"],
    "Dos Xx Lager Bottle": ["Prem Bottle", "Mexi Bottles"],
    "Truly Pineapple": ["Hard Seltzer"],
    "Truly Pineapple (Fs)": ["Hard Seltzer"],
    "Coronita Bottle": ["Cans / Prem Bottle", "Mexi Bottles"],

    # Drafts that didn't categorize
    "805 16Oz": ["Prem Pint"],
    "805 32Oz": ["Prem 32oz"],
    "805 Pitcher": ["Prem Pitcher"],
    "Alaskan Amber 16Oz": ["Prem Pint"],
    "Alaskan Amber 32Oz": ["Prem 32oz"],
    "Blue Moon 16Oz": ["Prem Pint"],
    "Blue Moon 32Oz": ["Prem 32oz"],
    "Bud Light 16Oz": ["Dom Pint"],
    "Bud Light 32Oz": ["Dom 32oz"],
    "Church Music 16Oz": ["Craft Pints"],
    "Church Music 32Oz": ["Craft Pints"],
    "Coors Light 16Oz": ["Dom Pint"],
    "Coors Light 32Oz": ["Dom 32oz"],
    "Dos Xx Lager 16Oz": ["Prem Pint"],
    "Dos Xx Lager 32Oz": ["Prem 32oz"],
    "Dos Xx Lager Pitcher": ["Prem Pitcher"],
    "Juicy Haze 16Oz": ["Prem Pint"],
    "Juicy Haze 32Oz": ["Prem 32oz"],
    "Lagunitas Ipa 16Oz": ["Craft Pints"],
    "Lagunitas Ipa 32Oz": ["Craft 32oz"],
    "Lagunitas Ipa Pitcher": ["Craft Pints"],
    "Michelob Ultra 16Oz": ["Dom Pint"],
    "Michelob Ultra 32Oz": ["Dom 32oz"],
    "Miller Lite 16Oz": ["Dom Pint"],
    "Miller Lite 32Oz": ["Dom 32oz"],
    "Modelo Especial 16Oz": ["Prem Pint"],
    "Modelo Especial 32Oz": ["Prem 32oz"],
    "Tower Station 16Oz": ["Craft Pints"],
    "Tower Station 32Oz": ["Craft 32oz"],
    "Zipps Lager 16Oz": ["Craft Pints"],
    "Zipps Lager 32Oz": ["Craft 32oz"],
    "Zipps Lager Pitcher": ["Craft Pitcher"],

    # Domestic Draft
    "Bud Light 16oz": ["Dom Pint"],
    "Bud Light 32oz": ["Dom 32oz"],
    "Bud Light Pitcher": ["Dom Pitcher"],
    "Coors Light 16oz": ["Dom Pint"],
    "Coors Light 32oz": ["Dom 32oz"],
    "Coors Light Pitcher": ["Dom Pitcher"],
    "Michelob Ultra 16oz": ["Dom Pint"],
    "Michelob Ultra 32oz": ["Dom 32oz"],
    "Michelob Ultra Pitcher": ["Dom Pitcher"],
    "Miller Lite 16oz": ["Dom Pint"],
    "Miller Lite 32oz": ["Dom 32oz"],
    "Miller Lite Pitcher": ["Dom Pitcher"],

    # Premium Draft
    "Dos XX Lager 16oz": ["Prem Pint"],
    "Dos XX Lager 32oz": ["Prem 32oz"],
    "Dos XX Lager Pitcher": ["Prem Pitcher"],
    "Modelo Especial 16oz": ["Prem Pint"],
    "Modelo Especial 32oz": ["Prem 32oz"],
    "Modelo Especial Pitcher": ["Prem Pitcher"],
    "Blue Moon 16oz": ["Prem Pint"],
    "Blue Moon 32oz": ["Prem 32oz"],
    "Blue Moon Pitcher": ["Prem Pitcher"],
    "Alaskan Amber 16oz": ["Prem Pint"],
    "Alaskan Amber 32oz": ["Prem 32oz"],
    "Alaskan Amber Pitcher": ["Prem Pitcher"],
    "Juicy Haze 16oz": ["Prem Pint"],
    "Juicy Haze 32oz": ["Prem 32oz"],
    "Juicy Haze Pitcher": ["Prem Pitcher"],

    # Craft Draft
    "Church Music 16oz": ["Craft Pints"],
    "Church Music 32oz": ["Craft Pints"],
    "Church Music Pitcher": ["Craft Pitcher"],
    "Lagunitas IPA 16oz": ["Craft Pints"],
    "Lagunitas IPA 32oz": ["Craft Pints"],
    "Lagunitas IPA Pitcher": ["Craft Pitcher"],
    "Tower Station 16oz": ["Craft Pints"],
    "Tower Station 32oz": ["Craft Pints"],
    "Tower Station Pitcher": ["Craft Pitcher"],
    "Zipps Lager 16oz": ["Craft Pints"],
    "Zipps Lager 32oz": ["Craft Pints"],

    # House Wines $5
    "House Cab GL": ["House Wines"],
    "House Cab Gl": ["House Wines"],
    "House Chard GL": ["House Wines"],
    "House Chard Gl": ["House Wines"],
    "House White Zin GL": ["House Wines"],
    "House Merlot GL": ["House Wines"],
    "House Merlot Gl": ["House Wines"],
    "House White Zin Gl": ["House Wines"],

    # Premium Wines
    "20 Acres Cab GL": ["Prem Wines"],
    "Champagne GL": ["Prem Wines"],
    "Infamous Goose Sauv Blanc GL": ["Prem Wines"],
    "Kendall Jackson Chard GL": ["Prem Wines"],
    "La Crema Chard GL": ["Prem Wines"],
    "La Crema Pinot Noir GL": ["Prem Wines"],
    "La Marca Prosecco GL": ["Prem Wines"],
    "Troublemaker Red Blend GL": ["Prem Wines"],
    "Villa Sandi Pinot Grigio GL": ["Prem Wines"],

    # Mimosa $5
    "Mimosa": ["Mimosa"],
    "Mimosa Fs": ["Mimosa"],

    # Liquor
    "Old Fashion Bulleit Rye": ["Bulleit Old Fashioned"],
    "Crown Royal (Fs)": ["Crown Royal"],
    "Crown Royal": ["Crown Royal"],
    "Crown Apple (Fs)": ["Crown Royal"],
    "Crown Apple": ["Crown Royal"],
    "Desert Donkey Milagro": ["Desert Donkey Milagro"],
    "Desert Donkey Titos": ["Desert Donkey Tito's"],
    "Fireball": ["Fireball"],
    "Fireball (Fs)": ["Fireball"],
    "Four Roses Bourbon (Fs)": ["Four Roses"],
    "Four Roses Bourbon": ["Four Roses"],
    "Old Fashion Four Roses": ["Four Roses Old Fashioned"],
    "Green Tea": ["Green Tea"],
    "Hendricks": ["Hendricks"],
    "Hendricks (Fs)": ["Hendricks"],
    "Iceberg": ["Iceberg"],
    "Jack Daniels": ["Jack Daniels"],
    "Jack Daniels (Fs)": ["Jack Daniels"],
    "Jameson": ["Jameson"],
    "Jameson (Fs)": ["Jameson"],
    "Ketel One": ["Ketel One"],
    "Ketel One (Fs)": ["Ketel One"],
    "Milagro Anejo": ["Milagro (Anejo)"],
    "Milagro Silver & Rep": ["Milagro (Silver & Rep)"],
    "Titos": ["Tito'S"],
    "Milagro Anejo (Fs)": ["Milagro (Anejo)"],
    "Milagro Silver & Rep (Fs)": ["Milagro (Silver & Rep)"],
    "Screwball": ["Screwballs"],
    "Screwball (Fs)": ["Screwballs"],
    "Titos (Fs)": ["Tito'S"],
    "Titos Bloody": ["Tito's Screw/Bloody"],
    "Titos Screw": ["Tito's Screw/Bloody"],
    "Well Whiskey": ["Well"],
    "Well Whiskey (Fs)": ["Well"],
    "Well Gin": ["Well"],
    "Well Gin (Fs)": ["Well"],
    "Well Vodka": ["Well"],
    "Well Vodka (Fs)": ["Well"],
    "Well Rum": ["Well"],
    "Well Rum (Fs)": ["Well"],
    "Well Scotch": ["Well"],
    "Well Scotch (Fs)": ["Well"],
    "Double Well": ["Well"],
    "Western Son": ["WS Sons Vodka"],
    "Western Son (Fs)": ["WS Sons Vodka"],
    "Western Son Blueberry": ["WS Sons Vodka"],
    "Western Son Raspberry (Fs)": ["WS Sons Vodka"],
    "Western Son Lemon": ["WS Sons Vodka"],
    "Western Son Lemon (Fs)": ["WS Sons Vodka"],
    "Western Son Prickly Pear": ["WS Sons Vodka"],
    "Western Son Prickly Pear (Fs)": ["WS Sons Vodka"],
    "Western Son Prickly Pear (Bump)": ["WS Sons Vodka"],
    "Western Son Raspberry": ["WS Sons Vodka"],
    "Zipparita": ["Zipparita"],
    "Zipparita Straw": ["Zipparita Flavored"],

    # More liquor
    "Jack Fire": ["Jack Daniels"],
    "Jack Fire (Fs)": ["Jack Daniels"],
    "Milagro": ["Milagro (Silver & Rep)"],
    "Milagro (Fs)": ["Milagro (Silver & Rep)"],
    "Milagro Reposado": ["Milagro (Silver & Rep)"],
    "Milagro Reposado (Fs)": ["Milagro (Silver & Rep)"],
    "Well Tequila": ["Well"],
    "Well Tequila (Fs)": ["Well"],
    "20 Acres Cab Gl": ["Prem Wines"],
    "Champagne Gl": ["Prem Wines"],
    "Infamous Goose Sauv Blanc Gl": ["Prem Wines"],
    "Kendall Jackson Chard Gl": ["Prem Wines"],
    "La Crema Chard Gl": ["Prem Wines"],
    "La Crema Pinot Noir Gl": ["Prem Wines"],
    "La Marca Prosecco Gl": ["Prem Wines"],
    "Troublemaker Red Blend Gl": ["Prem Wines"],
    "Villa Sandi Pinot Grigio Gl": ["Prem Wines"],

    # Food items
    "1000 Island": ["Other"],
    "Add All White": ["Add Ons"],
    "Add Bacon": ["Add Ons"],
    "Add Black Beans (Nachos)": ["Add Ons"],
    "Add Black Olives": ["Add Ons"],
    "Add Black Olives (Nachos)": ["Add Ons"],
    "Add Cheddar": ["Add Ons"],
    "Add Cheese (Soups)": ["Add Ons"],
    "Add Corn (Zipps Nachos)": ["Add Ons"],
    "Add Golden Sauce": ["Add Ons"],
    "Add Jalp": ["Add Ons"],
    "Add Jalp (Zipps Nachos)": ["Add Ons"],
    "Add Lettuce": ["Add Ons"],
    "Add Mozzarella": ["Add Ons"],
    "Add Onions (Soups)": ["Add Ons"],
    "Add Pepper Jack": ["Add Ons"],
    "Add Pickled Jalapenos (Nachos)": ["Add Ons"],
    "Add Sauteed Mush": ["Add Ons"],
    "Add Shredded Chicken (Nachos)": ["Add Ons"],
    "Add Sirloin (Nachos)": ["Add Ons"],
    "Add Swiss": ["Add Ons"],
    "Balsamic Vinaigrette": ["Dressings / Sauces"],
    "Blue Cheese": ["Dressings / Sauces"],
    "Caesar": ["Dressings / Sauces"],
    "Extra Hot": ["Wing Sauces"],
    "French Fries (Basket)": ["Baskets"],
    "Honey Balsamic": ["Dressings / Sauces"],
    "Honey Mustard": ["Dressings / Sauces"],
    "Hot": ["Wing Sauces"],
    "Lemon Vinaigrette": ["Dressings / Sauces"],
    "Lt. Olive Vin": ["Dressings / Sauces"],
    "Medium": ["Wing Sauces"],
    "Mild": ["Wing Sauces"],
    "Oil & Vinegar": ["Dressings / Sauces"],
    "Onion Rings (Basket)": ["Baskets"],
    "Ranch": ["Dressings / Sauces"],
    "Sour Cream Add On": ["Add Ons"],
    "Sweet Jalapeno": ["Dressings / Sauces"],
    "Sweet Potato Chips (Basket)": ["Baskets"],
    "Toss In Golden": ["Add Ons"],
    "Baskets": ["Baskets"],
    "Buffalo Wings": ["Wings"],
    "Chicken Fingers": ["Chicken Fingers"],
    "Chix Quesadilla": ["Quesadillas"],
    "Golden Wings": ["Wings"],
    "Mozzarella Sticks": ["Appetizers"],
    "Quesadilla": ["Quesadillas"],
    "Sirloin Quesadilla": ["Quesadillas"],
    "1000 Island Burger": ["Burgers"],
    "Bacon Cheeseburger": ["Burgers"],
    "Bbq Bacon Burger": ["Burgers"],
    "Big Zipp Burger": ["Burgers"],
    "Black & Blue Burger": ["Burgers"],
    "Cado Burger": ["Burgers"],
    "Egg It!": ["Burger Add Ons"],
    "Green Chili Burger": ["Burgers"],
    "Mushroom Swiss Burger": ["Burgers"],
    "No Onions (Burger)": ["Burger Modifications"],
    "No Pickles": ["Burger Modifications"],
    "Peanut Butter Burger": ["Burgers"],
    "Sweet Jalapeno Burger": ["Burgers"],
    "Turkey Burger": ["Burgers"],
    "Turkey Patty": ["Burger Modifications"],
    "Veggie Burger": ["Burgers"],
    "Veggie Patty": ["Burger Modifications"],
    "Zipps Burger": ["Burgers"],
    "Classic Root Beer Float": ["Desserts"],
    "Scoop Of Vanilla 1": ["Add Ons"],
    "Scoop Of Vanilla 2": ["Add Ons"],
    "Jimmy It!": ["Focaccia Modifications"],
    "Scorch Focaccia": ["Focaccia"],
    "Steak Philly Focaccia": ["Focaccia"],
    "Tenderloin Focaccia": ["Focaccia"],
    "Carrots And Ranch": ["Sides"],
    "Kids 2 Slices Of Cheese Pizza": ["Kids Menu"],
    "Kids Carrots And Ranch": ["Kids Menu"],
    "Kids Chicken Fingers": ["Kids Menu"],
    "Kids Chicken Skewers": ["Kids Menu"],
    "Kids Grilled Cheese": ["Kids Menu"],
    "Kids Quesadilla": ["Kids Menu"],
    "Kids Zipps Burger": ["Kids Menu"],
    "Kids Zipps Cheese Burger": ["Kids Menu"],
    "Arnold Palmer": ["Non-Alcoholic Beverages"],
    "Coke": ["Non-Alcoholic Beverages"],
    "Coke Mixer": ["Mixers"],
    "Coke Zero": ["Non-Alcoholic Beverages"],
    "Cranberry Juice Mixer": ["Mixers"],
    "Diet Coke": ["Non-Alcoholic Beverages"],
    "Diet Coke Mixer": ["Mixers"],
    "Iced Tea": ["Non-Alcoholic Beverages"],
    "Kids Lemonade": ["Kids Menu"],
    "Kids Milk": ["Kids Menu"],
    "Kids Mr. Pibb": ["Kids Menu"],
    "Kids Root Beer": ["Kids Menu"],
    "Lemonade": ["Non-Alcoholic Beverages"],
    "Mr. Pibb": ["Non-Alcoholic Beverages"],
    "Red Bull Mixer": ["Mixers"],
    "Root Beer": ["Non-Alcoholic Beverages"],
    "Sf Red Bull": ["Non-Alcoholic Beverages"],
    "Soda Mixer": ["Mixers"],
    "Soda Water": ["Mixers"],
    "Sprite": ["Non-Alcoholic Beverages"],
    "Sprite Mixer": ["Mixers"],
    "Straw Lemonade": ["Non-Alcoholic Beverages"],
    "Tonic Mixer": ["Mixers"],
    "Zipps Water": ["Non-Alcoholic Beverages"],
    "Beef Sirloin Taco": ["Tacos"],
    "Chicken Taco": ["Tacos"],
    "Fish And Chips": ["Fish Entrees"],
    "Buffalo Chicken Salad": ["Salads"],
    "Caesar Salad": ["Salads"],
    "Chicken Caesar Salad": ["Salads"],
    "Chicken Greek Salad": ["Salads"],
    "Fried Chicken Salad": ["Salads"],
    "Honey Balsamic Salad": ["Salads"],
    "House Salad": ["Salads"],
    "Side Salad (Zipps)": ["Sides"],
    "Sirloin Taco Salad": ["Salads"],
    "Zipps Chop Salad": ["Salads"],
    "B.L.T. On Sdb": ["Sandwiches"],
    "Bbq Chicken Sandwich": ["Sandwiches"],
    "Chicken Club Sandwich": ["Sandwiches"],
    "Club Sandwich": ["Sandwiches"],
    "Southwest Chicken Sandwich": ["Sandwiches"],
    "Spicy Chix Sandwich": ["Sandwiches"],
    "Turkey Sandwich": ["Sandwiches"],
    "1/2 Fries 1/2 Chips": ["Sides"],
    "1/2 Fries 1/2 Onion Rings": ["Sides"],
    "1/2 Onion Rings 1/2 Chips": ["Sides"],
    "Bbq Sauce": ["Dressings / Sauces"],
    "Bulk Dressing": ["Dressings / Sauces"],
    "Chip Refill": ["Add Ons"],
    "Extra Dressing": ["Add Ons"],
    "French Fries": ["Sides"],
    "Kids French Fries": ["Kids Menu"],
    "Onion Rings": ["Sides"],
    "Salsa Refill": ["Add Ons"],
    "Side Bbq Sauce": ["Dressings / Sauces"],
    "Side Beer Cheese": ["Dressings / Sauces"],
    "Side Buffalo Sauce": ["Dressings / Sauces"],
    "Side Chipotle Mayo": ["Dressings / Sauces"],
    "Side Golden Sauce": ["Dressings / Sauces"],
    "Side Jalapenos": ["Add Ons"],
    "Side Mayo": ["Dressings / Sauces"],
    "Side Pickle Chips": ["Add Ons"],
    "Side Pico De Gallo": ["Add Ons"],
    "Side Salad": ["Sides"],
    "Side Sour Cream": ["Add Ons"],
    "Sweet Potato Chips": ["Sides"],
    "Green Bay Chili Bowl": ["Soups / Chili"],
    "S.O.D. Bowl": ["Soups / Chili"],
    "S.O.D. Cup": ["Soups / Chili"],
    "Sub Carrots & Celery": ["Substitutions"],
    "Sub Casear Salad": ["Substitutions"],
    "Sub Pepper Jack": ["Substitutions"],
    "Sub Provolone": ["Substitutions"],
    "Sub Turkey Patty": ["Substitutions"],
    "Ground Beef Topping (Slice)": ["Pizza Toppings"],
    "Pepperoni Topping (Slice)": ["Pizza Toppings"],
    "Sausage Topping (Slice)": ["Pizza Toppings"],
    "Slice Of Pizza": ["Pizza Slices"],
    "Makers Mark": ["Makers Mark"],
    "Kahlua (Fs)": ["Kahlua"],
    "Big Zipparita": ["Zipparita"],
    "Bloody Mary": ["Bloody Mary"],
    "Chambord Flavor": ["Flavor Shots"],
    "Chambord Flavor 24Oz To Go": ["Flavor Shots"],
    "Espresso Martini": ["Martinis"],
    "Firecracker Flavor": ["Flavor Shots"],
    "Firecracker Flavor 24Oz To Go": ["Flavor Shots"],
    "Gran Mar Flavor": ["Flavor Shots"],
    "Gran Mar Flavor 24Oz To Go": ["Flavor Shots"],
    "Gran Mar Flavor Big Rita": ["Flavor Shots"],
    "Grateful Flavor": ["Flavor Shots"],
    "Mango Flavor": ["Flavor Shots"],
    "Melon Flavor": ["Flavor Shots"],
    "Milagro Anejo Flavor": ["Flavor Shots"],
    "Milagro Margarita": ["Milagro Margarita"],
    "Milagro Silver Flavor": ["Flavor Shots"],
    "Moscow Mule Titos": ["Moscow Mules"],
    "Peach Flavor": ["Flavor Shots"],
    "Strawberry Flavor": ["Flavor Shots"],
    "To Go Rita 24Oz": ["To Go Drinks"],
    "Watermelon Flavor": ["Flavor Shots"],
    "White Tea": ["White Tea"],
    "Captain Morgan": ["Captain Morgan"],
    "Patron Silver": ["Patron Silver"],
    "Ketel One (Bump)": ["Ketel One"],
    "Martini Up": ["Martinis"],
    "Cranberry Back": ["Mixers"],
    "Western Son Blueberry (Fs)": ["WS Sons Vodka"],
    "House Wine": ["House Wines"],
    "Premium Wine": ["Prem Wines"],
    "Beer Cheese Pretzels": ["Beer Cheese"],
    "Chicken Rolls": ["Chicken Rolls"],
    "Chicken Skewers": ["Chicken Skewers"],
    "Chips, Salsa & Guac": ["Chips, Salsa & Guac"],
    "Corn Dog Basket": ["Corn Dogs"],
    "Nachos (Zipps)": ["Nachos"],
    "Philly Steak Rolls": ["Philly Rolls"],
    "Brownie Skillet": ["Dessert Skillets"],
    "Choc Chip Cookie Skillet": ["Dessert Skillets"],
    "White Choc Cookie Skillet": ["Dessert Skillets"],
    "Zippapillas": ["Zippapillas"],
    "Buffalo Focaccia": ["Focaccia - (All Other Chicken)"],
    "Chicken Caesar Focaccia": ["Focaccia - (All Other Chicken)"],
    "Chicken Focaccia": ["Focaccia - Chicken, Club"],
    "Chicken Philly Focaccia": ["Focaccia - (All Other Chicken)"],
    "Club Focaccia": ["Focaccia - Chicken, Club"],
    "Golden Focaccia": ["Focaccia - (All Other Chicken)"],
    "Monaco Focaccia": ["Focaccia - (All Other Chicken)"],
    "Pepper Jack Focaccia": ["Focaccia - (All Other Chicken)"],
    "Scorch Focaccia:": ["Focaccia - (All Other Chicken)"],
    "Chicken Burrito": ["Burritos (All)"],
    "Fish Taco": ["Tacos-Fish"],
    "Sirloin Burrito": ["Burritos (All)"],
    "Tacos": ["Tacos - Chicken/Sirloin"],
    "Zipps Dog": ["Zipps Dog"],
    "Fish And Chips ": ["Fish Entrees (All)"],
    '18" Pizza Pie': ['Pizza 18" Whole'],
    '18" Pizza Pie ': ['Pizza 18" Whole'],
}

key_to_sheet_label = {
    "Dom Bottle $4.50": "Dom Bottle $4.50",
    "Dom Bottle $5.00": "Dom Bottle $5",
    "Dom Bottle $5": "Dom Bottle $5",
    "Cans / Prem Bottle $5.00": "Cans / Prem Bottle $5",
    "Cans / Prem Bottle $5": "Cans / Prem Bottle $5",
    "Mexi Bottles $5.50": "Mexi Bottles $5.50",
    "Hard Seltzers $5.00": "Hard Seltzers $5",
    "Hard Seltzers $5": "Hard Seltzers $5",
    "Hard Seltzers $5.50": "Hard Seltzers $5.50",
    "Hard Seltzer $5.00": "Hard Seltzer $5",
    "Hard Seltzer $5": "Hard Seltzer $5",
    "Hard Seltzer $5.50": "Hard Seltzer $5.50",
    "Dom Bucket $23.00": "Dom Bucket $23",
    "Dom Bucket $23": "Dom Bucket $23",
    "Coronita Bucket $24 $24": "Coronita Bucket $24",
    "Zipparona $14.00": "Zipparona $14",
    "Zipparona $14": "Zipparona $14",
    "Dom Pint $5.00": "Dom Pint $5",
    "Dom Pint $5": "Dom Pint $5",
    "Dom 32oz $7.00": "Dom 32oz $7",
    "Dom 32oz $7": "Dom 32oz $7",
    "Prem Pint $5.00": "Prem Pint $5",
    "Prem Pint $5": "Prem Pint $5",
    "Prem Pint $5.50": "Prem Pint $5.50",
    "Craft Pints $5.00": "Craft Pints $5",
    "Craft Pints $5": "Craft Pints $5",
    "Craft Pints $5.50": "Craft Pints $5.50",
    "Prem Pitcher $14.00": "Prem Pitcher $14",
    "Prem Pitcher $14": "Prem Pitcher $14",
    "House Wines $5.00": "House Wines $5",
    "House Wines $5": "House Wines $5",
    "Prem Wines $7.00": "Prem Wines $7",
    "Prem Wines $7": "Prem Wines $7",
    "Prem Wines $8.00": "Prem Wines $8",
    "Prem Wines $8": "Prem Wines $8",
    "Mimosa $5.00": "Mimosa $5",
    "Mimosa $5": "Mimosa $5",
    "Bulleit Old Fashioned $8.00": "Bulleit Old Fashioned $8",
    "Bulleit Old Fashioned $8": "Bulleit Old Fashioned $8",
    "Crown Royal $6.50": "Crown Royal $6.50",
    "Desert Donkey Milagro $7.50": "Desert Donkey Milagro $7.50",
    "Desert Donkey Tito's $7.50": "Desert Donkey Tito's $7.50",
    "Fireball $4.00": "Fireball $4",
    "Fireball $4": "Fireball $4",
    "Four Roses $5.00": "Four Roses $5",
    "Four Roses $5": "Four Roses $5",
    "Four Roses $5.50": "Four Roses $5.50",
    "Four Roses Old Fashioned $8.00": "Four Roses Old Fashioned $8",
    "Four Roses Old Fashioned $8": "Four Roses Old Fashioned $8",
    "Green Tea $5.00": "Green Tea $5",
    "Green Tea $5": "Green Tea $5",
    "Hendricks $6.50": "Hendricks $6.50",
    "Iceberg $0.75": "Iceberg $0.75",
    "Jack Daniels $5.00": "Jack Daniels $5",
    "Jack Daniels $5": "Jack Daniels $5",
    "Jack Daniels $5.50": "Jack Daniels $5.50",
    "Jack Daniels $6.50": "Jack Daniels $6.50",
    "Jameson $5.00": "Jameson $5",
    "Jameson $5": "Jameson $5",
    "Jameson $5.50": "Jameson $5.50",
    "Jameson $6.50": "Jameson $6.50",
    "Ketel One $5.00": "Ketel One $5",
    "Ketel One $5": "Ketel One $5",
    "Ketel One $6.50": "Ketel One $6.50",
    "Milagro (Anejo) $5.00": "Milagro (Anejo) $5",
    "Milagro (Anejo) $5": "Milagro (Anejo) $5",
    "Milagro (Anejo) $5.50": "Milagro (Anejo) $5.50",
    "Milagro (Anejo) $6.50": "Milagro (Anejo) $6.50",
    "Milagro (Silver & Rep) $5.00": "Milagro (Silver & Rep) $5",
    "Milagro (Silver & Rep) $5.0": "Milagro (Silver & Rep) $5",
    "Milagro (Silver & Rep) $5": "Milagro (Silver & Rep) $5",
    "Milagro (Silver & Rep) $5.50": "Milagro (Silver & Rep) $5.50",
    "Milagro (Silver & Rep) $6.50": "Milagro (Silver & Rep) $6.50",
    "Screwballs $4.00": "Screwballs $4",
    "Screwballs $4": "Screwballs $4",
    "Tito'S $5.50": "Tito'S $5.50",
    "Tito'S $6.50": "Tito'S $6.50",
    "Tito's Screw/Bloody $6.50": "Tito's Screw/Bloody $6.50",
    "Well $4.25": "Well $4.25",
    "WS Sons Vodka $4.00": "WS Sons Vodka $4",
    "WS Sons Vodka $4": "WS Sons Vodka $4",
    "Zipparita $5.00": "Zipparita $5",
    "Zipparita $5.0": "Zipparita $5",
    "Zipparita $5": "Zipparita $5",
    "Zipparita $5.50": "Zipparita $5.50",
    "Zipparita Flavored $6.25": "Zipparita Flavored $6.25",
    "Zipparita Flavored $6.75": "Zipparita Flavored $6.75",
    "Beer Cheese $7.00": "Beer Cheese $7",
    "Beer Cheese $7": "Beer Cheese $7",
    "Beer Cheese $8.00": "Beer Cheese $8",
    "Beer Cheese $8": "Beer Cheese $8",
    "Burritos (All) $7.00": "Burritos (All) $7",
    "Burritos (All) $7": "Burritos (All) $7",
    "Chicken Rolls $7.00": "Chicken Rolls $7",
    "Chicken Rolls $7": "Chicken Rolls $7",
    "Chicken Skewers $12.00": "Chicken Skewers $12",
    "Chicken Skewers $12": "Chicken Skewers $12",
    "Chips, Salsa & Guac $5.50": "Chips, Salsa, & Guac $5.50",
    "Chips, Salsa, & Guac $5.50": "Chips, Salsa, & Guac $5.50",
    "Corn Dogs $7.00": "Corn Dogs $7",
    "Corn Dogs $7": "Corn Dogs $7",
    "Dessert Skillets $8.00": "Dessert Skillets $8",
    "Dessert Skillets $8": "Dessert Skillets $8",
    "Fish Entrees (All) $9.00": "Fish Entrees (All) $9",
    "Fish Entrees (All) $9.0": "Fish Entrees (All) $9",
    "Fish Entrees (All) $9": "Fish Entrees (All) $9",
    "Focaccia - (All Other Chicken) $12.00": "Focaccia - (All Other Chicken) $12",
    "Focaccia - (All Other Chicken) $12": "Focaccia - (All Other Chicken) $12",
    "Focaccia - Chicken, Club $12.00": "Focaccia - Chicken, Club $12",
    "Focaccia - Chicken, Club $12": "Focaccia - Chicken, Club $12",
    "Nachos $8.00": "Nachos $8",
    "Nachos $8": "Nachos $8",
    "Philly Rolls $7.00": "Philly Rolls $7",
    "Philly Rolls $7": "Philly Rolls $7",
    "Pizza Slices $3.25": "Pizza Slices $3.25",
    'Pizza 18" Whole $16.00': 'Pizza 18" Whole $16',
    'Pizza 18" Whole $16': 'Pizza 18" Whole $16',
    "Tacos - Chicken/Sirloin $7.00": "Tacos - Chicken/Sirloin $7",
    "Tacos - Chicken/Sirloin $7": "Tacos - Chicken/Sirloin $7",
    "Tacos - Fish $7.00": "Tacos - Fish $7",
    "Tacos - Fish $7": "Tacos - Fish $7",
    "Tacos-Fish $7.00": "Tacos-Fish $7",
    "Tacos-Fish $7": "Tacos-Fish $7",
    "Zippapillas $7.00": "Zippapillas $7",
    "Zippapillas $7": "Zippapillas $7",
    "Zipps Dog $7.00": "Zipps Dog $7",
    "Zipps Dog $7": "Zipps Dog $7",
    "Fish And Chips $9.00": "Fish Entrees (All) $9",
    "Fish And Chips $9": "Fish Entrees (All) $9",
}

DESIRED_ORDER_FINAL_CSV = [
    "Dom Bottle $4.50",
    "Dom Bottle $5",
    "Cans / Prem Bottle $5",
    "Mexi Bottles $5.50",
    "Hard Seltzer $5",
    "Hard Seltzer $5.50",
    "Hard Seltzers $5",
    "Hard Seltzers $5.50",
    "Dom Bucket $23",
    "Coronita Bucket $24",
    "Zipparona $14",
    "Dom Pint $5",
    "Dom 32oz $7",
    "Prem Pint $5",
    "Prem Pint $5.50",
    "Craft Pints $5",
    "Craft Pints $5.50",
    "Prem Pitcher $14",
    "House Wines $5",
    "Prem Wines $7",
    "Prem Wines $8",
    "Mimosa $5",
    "Bulleit Old Fashioned $8",
    "Crown Royal $6.50",
    "Desert Donkey Milagro $7.50",
    "Desert Donkey Tito's $7.50",
    "Fireball $4",
    "Four Roses $5",
    "Four Roses $5.50",
    "Four Roses Old Fashioned $8",
    "Green Tea $5",
    "Hendricks $6.50",
    "Iceberg $0.75",
    "Jack Daniels $5",
    "Jack Daniels $5.50",
    "Jack Daniels $6.50",
    "Jameson $5",
    "Jameson $5.50",
    "Jameson $6.50",
    "Ketel One $5",
    "Ketel One $6.50",
    "Milagro (Anejo) $5",
    "Milaglo (Anejo) $5.50",
    "Milagro (Anejo) $6.50",
    "Milagro (Silver & Rep) $5",
    "Milagro (Silver & Rep) $5.50",
    "Milagro (Silver & Rep) $6.50",
    "Screwballs $4",
    "Tito'S $5.50",
    "Tito'S $6.50",
    "Tito's Screw/Bloody $6.50",
    "Well $4.25",
    "WS Sons Vodka $4",
    "Zipparita $5",
    "Zipparita $5.50",
    "Zipparita Flavored $6.25",
    "Zipparita Flavored $6.75",
    "Beer Cheese $7",
    "Beer Cheese $8",
    "Burritos (All) $7",
    "Chicken Rolls $7",
    "Chicken Skewers $12",
    "Chips, Salsa, & Guac $5.50",
    "Corn Dogs $7",
    "Dessert Skillets $8",
    "Fish Entrees (All) $9",
    "Focaccia - (All Other Chicken) $12",
    "Focaccia - Chicken, Club $12",
    "Nachos $8",
    "Philly Rolls $7",
    "Pizza Slices $3.25",
    'Pizza 18" Whole $16',
    "Tacos - Chicken/Sirloin $7",
    "Tacos-Fish $7",
    "Zippapillas $7",
    "Zipps Dog $7",
]

DESIRED_ORDER_DISPLAY = [
    "Dom Bottle $4.50",
    "Dom Bottle $5",
    "Cans / Prem Bottle $5",
    "Mexi Bottles $5.50",
    "Hard Seltzer $5",
    "Hard Seltzer $5.50",
    "Dom Bucket $23",
    "Coronita Bucket $24",
    "Zipparona $14",
    None,
    "Dom Pint $5",
    "Dom 32oz $7",
    "Prem Pint $5",
    "Prem Pint $5.50",
    "Craft Pints $5",
    "Craft Pints $5.50",
    "Prem Pitcher $14",
    None,
    "House Wines $5",
    "Prem Wines $7",
    "Prem Wines $8",
    "Mimosa $5",
    None,
    "Bulleit Old Fashioned $8",
    "Crown Royal $6.50",
    "Desert Donkey Milagro $7.50",
    "Desert Donkey Tito's $7.50",
    "Fireball $4",
    "Four Roses $5",
    "Four Roses $5.50",
    "Four Roses Old Fashioned $8",
    "Green Tea $5",
    "Hendricks $6.50",
    "Iceberg $0.75",
    "Jack Daniels $5",
    "Jack Daniels $5.50",
    "Jack Daniels $6.50",
    "Jameson $5",
    "Jameson $5.50",
    "Jameson $6.50",
    "Ketel One $5",
    "Ketel One $6.50",
    "Milagro (Anejo) $5",
    "Milagro (Anejo) $5.50",
    "Milagro (Anejo) $6.50",
    "Milagro (Silver & Rep) $5",
    "Milagro (Silver & Rep) $5.50",
    "Milagro (Silver & Rep) $6.50",
    "Screwballs $4",
    "Tito'S $5.50",
    "Tito'S $6.50",
    "Tito's Screw/Bloody $6.50",
    "Well $4.25",
    "WS Sons Vodka $4",
    "Zipparita $5",
    "Zipparita $5.50",
    "Zipparita Flavored $6.25",
    "Zipparita Flavored $6.75",
    None,
    "Beer Cheese $7",
    "Beer Cheese $8",
    "Burritos (All) $7",
    "Chicken Rolls $7",
    "Chicken Skewers $12",
    "Chips, Salsa, & Guac $5.50",
    "Corn Dogs $7",
    "Dessert Skillets $8",
    "Fish Entrees (All) $9",
    "Focaccia - (All Other Chicken) $12",
    "Focaccia - Chicken, Club $12",
    "Nachos $8",
    "Philly Rolls $7",
    "Pizza Slices $3.25",
    'Pizza 18" Whole $16',
    "Tacos - Chicken/Sirloin $7",
    "Tacos-Fish $7",
    "Zippapillas $7",
    "Zipps Dog $7",
]


def process_data(input_df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Process sales mix data from a CSV file.

    Args:
        input_df: DataFrame with sales data (Item, Price, Items Sold columns)

    Returns:
        Tuple of (final_ordered_df, final_display_df)
    """
    df = input_df.rename(columns={input_df.columns[0]: 'Item'}).copy()

    df['Price'] = df['Price'].astype(str).str.replace('$', '', regex=False)
    df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
    df['Items Sold'] = pd.to_numeric(df['Items Sold'], errors='coerce')
    df = df.dropna(subset=['Items Sold', 'Price'])

    df['Item'] = (
        df['Item']
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
        .str.title()
    )

    agg_dict = {"Items Sold": "sum"}
    if '% Sales' in df.columns:
        agg_dict['% Sales'] = 'first'

    summary = (
        df.groupby(["Item", "Price"], dropna=False)
        .agg(agg_dict)
        .reset_index()
    )
    summary = summary.dropna(subset=['Price'])

    summary["CategoryList"] = summary["Item"].map(item_to_category)
    summary = summary.dropna(subset=["CategoryList"])
    summary = summary.explode("CategoryList")

    summary["CategoryList_str"] = summary["CategoryList"].astype(str)

    summary["Key"] = summary["CategoryList_str"] + " $" + summary["Price"].astype(str)
    summary["Key"] = summary["Key"].str.replace(r"\.0$", "", regex=True)

    summary["Key"] = summary["Key"].apply(
        lambda x: x if "$" not in x else (
            x + "0" if (("." in x.split('$')[-1]) and (len(x.split('$')[-1].split('.')[-1]) == 1))
            else x
        )
    )

    summary["DiscountSheetLabel"] = summary["Key"].map(key_to_sheet_label)
    summary = summary.dropna(subset=["DiscountSheetLabel"])

    final_df = (
        summary.groupby("DiscountSheetLabel")["Items Sold"]
        .sum()
        .reset_index()
    )

    # Create final_ordered_df for CSV export
    final_temp_for_ordering = final_df.copy()
    final_temp_for_ordering['DiscountSheetLabel'] = pd.Categorical(
        final_temp_for_ordering['DiscountSheetLabel'],
        categories=DESIRED_ORDER_FINAL_CSV,
        ordered=True
    )
    final_ordered_df = final_temp_for_ordering.sort_values('DiscountSheetLabel').dropna(subset=['DiscountSheetLabel'])

    # Create final_for_display_df for display (with breaks)
    final_for_display_df = pd.DataFrame({'DiscountSheetLabel': DESIRED_ORDER_DISPLAY})
    final_for_display_df = final_for_display_df.merge(final_df, on='DiscountSheetLabel', how='left')
    final_for_display_df['Items Sold'] = final_for_display_df['Items Sold'].fillna('')
    final_for_display_df = final_for_display_df[['DiscountSheetLabel', 'Items Sold']]

    return final_ordered_df, final_for_display_df
